### ISSUE TITLE
train error & eval visualization

### ISSUE THREAD

**Issue by haofanwang** [lisiyao21/Bailando#15]
1.  I meet error at Step 1 by running `python -u main.py --config configs/sep_vqvae.yaml --train`

```
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main()
  File "main.py", line 40, in main
    agent.train()
  File "/share/yanzhen/Bailando/motion_vqvae.py", line 94, in train
    loss.backward()
  File "/root/anaconda3/envs/workspace/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/anaconda3/envs/workspace/lib/python3.8/site-packages/torch/autograd/__init__.py", line 166, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_, is_grads_batched=False)
  File "/root/anaconda3/envs/workspace/lib/python3.8/site-packages/torch/autograd/__init__.py", line 67, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs
```

After print the loss, it looks like `tensor([0.2667, 0.2735, 0.2687, 0.2584, 0.2701, 0.2697, 0.2571, 0.2658],
       device='cuda:0', grad_fn=<GatherBackward>)`, so do I need to take mean or sum operation?

2. To eval, I run `python -u main.py --config configs/sep_vqvae.yaml --eval` with the provided ckpt, however, the visualized image only has half part as below. How to modify the pose position so that the full body can be seen?

![frame000000](https://user-images.githubusercontent.com/18741068/167408841-75d73360-f36c-4804-8d1e-3b469c1dade9.png)

**Comment by aleeyang** [comment]
@haofanwang have you solved this problem? I meet the same problem

**Comment by uk9921** [comment]
Are you using multiple GPUs for training?
Maybe specifying the GPU index would help 
`CUDA_VISIBLE_DEVICES=0 python -u main.py --config configs/sep_vqvae.yaml --train`
