### ISSUE TITLE
ValueError: only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by aleeyang** [lisiyao21/Bailando#25]
hey, I face this problem using the first step command
`python -u main.py --config configs/sep_vqvae.yaml --train`
THE OUTPUT IS 
`using SepVQVAE
We use bottleneck!
No motion regularization!
We use bottleneck!
No motion regularization!
train with AIST++ dataset!
test with AIST++ dataset!
{'structure': {'name': 'SepVQVAE', 'up_half': {'levels': 1, 'downs_t': [3], 'strides_t': [2], 'emb_width': 512, 'l_bins': 512, 'l_mu': 0.99, 'commit': 0.02, 'hvqvae_multipliers
': [1], 'width': 512, 'depth': 3, 'm_conv': 1.0, 'dilation_growth_rate': 3, 'sample_length': 240, 'use_bottleneck': True, 'joint_channel': 3, 'vel': 1, 'acc': 1, 'vqvae_reverse
_decoder_dilation': True, 'dilation_cycle': None}, 'down_half': {'levels': 1, 'downs_t': [3], 'strides_t': [2], 'emb_width': 512, 'l_bins': 512, 'l_mu': 0.99, 'commit': 0.02, '
hvqvae_multipliers': [1], 'width': 512, 'depth': 3, 'm_conv': 1.0, 'dilation_growth_rate': 3, 'sample_length': 240, 'use_bottleneck': True, 'joint_channel': 3, 'vel': 1, 'acc':
 1, 'vqvae_reverse_decoder_dilation': True, 'dilation_cycle': None}, 'use_bottleneck': True, 'joint_channel': 3, 'l_bins': 512}, 'loss_weight': {'mse_weight': 1}, 'optimizer': 
{'type': 'Adam', 'kwargs': {'lr': 3e-05, 'betas': [0.5, 0.999], 'weight_decay': 0}, 'schedular_kwargs': {'milestones': [100, 200], 'gamma': 0.1}}, 'data': {'name': 'aist', 'tra
in_dir': 'data/aistpp_train_wav', 'test_dir': 'data/aistpp_test_full_wav', 'seq_len': 240, 'data_type': 'None'}, 'testing': {'height': 540, 'width': 960, 'ckpt_epoch': 500}, 'e
xpname': 'sep_vqvae', 'epoch': 500, 'batch_size': 32, 'save_per_epochs': 20, 'test_freq': 20, 'log_per_updates': 1, 'seed': 42, 'rotmat': False, 'cuda': True, 'global_vel': Fal
se, 'ds_rate': 8, 'move_train': 40, 'sample_code_length': 150, 'sample_code_rate': 16, 'analysis_sequence': [[126, 81]], 'config': 'configs/sep_vqvae.yaml', 'train': True, 'eva
l': False, 'visgt': False, 'anl': False, 'sample': False}
07/03/2022 03:06:44 Epoch: 1
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main()
  File "main.py", line 40, in main
    agent.train()
  File "/home/fuyang/project/Bailando/motion_vqvae.py", line 107, in train
    'loss': loss.item(),
**ValueError: only one element tensors can be converted to Python scalars**`
My environment is
pytorch 1.11.0+cu102
8xGPU NVIDIA TITAN Xp(12196MiB)

**Comment by aleeyang** [comment]
thank you! It works !
![image](https://user-images.githubusercontent.com/54769687/177969965-ea7349cf-041f-4cd7-85cc-daea5a25f542.png)
